apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::964170739707:role/eksctl-caregiverCluster-nodegroup--NodeInstanceRole-gupRrY2EqURs
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::964170739707:user/alex_chen
      username: alex_chen
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2023-11-30T03:37:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1450"
  uid: 45c318bb-bf2f-441d-bc5a-ceeb39efea11
